// Scopes the Sulcus Cloud stylesheet to the film's UI planes.
//
// src/ui/app.css is a byte-for-byte copy of the product's
// sulcus/cloud/static/app.css. Loaded as-is it would also restyle the film's
// own titles and Remotion Studio (it sets `body`, `*`, `:root`), so this
// rewrites every selector to live under `.sulcus-ui`, the root element of each
// UI plane, and writes src/ui/app.scoped.css. Nothing else changes: same
// rules, same values, same order.
//
//   node scripts/scope-ui-css.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCOPE = ".sulcus-ui";

const scopeSelector = (sel) => {
  const s = sel.trim();
  if (!s) return s;
  // The document-level selectors become the plane's root element.
  if (s === ":root" || s === "html" || s === "body") return SCOPE;
  if (s.startsWith("body.")) return SCOPE + s.slice(4);
  return `${SCOPE} ${s}`;
};

// Splits a selector list on top-level commas (not those inside :not(), :has()).
const splitList = (list) => {
  const out = [];
  let depth = 0;
  let cur = "";
  for (const ch of list) {
    if (ch === "(") depth++;
    if (ch === ")") depth--;
    if (ch === "," && depth === 0) {
      out.push(cur);
      cur = "";
    } else cur += ch;
  }
  out.push(cur);
  return out;
};

// Walks a block of CSS, scoping rules and recursing into @media.
const scope = (css) => {
  let out = "";
  let i = 0;
  while (i < css.length) {
    // Comments and whitespace pass through.
    if (css.startsWith("/*", i)) {
      const end = css.indexOf("*/", i) + 2;
      out += css.slice(i, end);
      i = end;
      continue;
    }
    if (/\s/.test(css[i])) {
      out += css[i++];
      continue;
    }
    const open = css.indexOf("{", i);
    if (open < 0) {
      out += css.slice(i);
      break;
    }
    const prelude = css.slice(i, open);
    // Find the matching close brace.
    let depth = 1;
    let j = open + 1;
    while (depth > 0 && j < css.length) {
      if (css[j] === "{") depth++;
      else if (css[j] === "}") depth--;
      j++;
    }
    const body = css.slice(open + 1, j - 1);
    const at = prelude.trim();
    if (at.startsWith("@media") || at.startsWith("@supports")) {
      out += `${prelude}{${scope(body)}}`;
    } else if (at.startsWith("@")) {
      out += `${prelude}{${body}}`; // @keyframes and friends: unchanged
    } else {
      const lead = prelude.match(/^\s*/)[0];
      out += lead + splitList(prelude).map(scopeSelector).join(", ") + ` {${body}}`;
    }
    i = j;
  }
  return out;
};

const src = fs.readFileSync(path.join(ROOT, "src/ui/app.css"), "utf8");
const header =
  "/* GENERATED by scripts/scope-ui-css.mjs from src/ui/app.css (Sulcus Cloud,\n" +
  "   sulcus/cloud/static/app.css). Do not edit; edit the source and rerun. */\n";
fs.writeFileSync(path.join(ROOT, "src/ui/app.scoped.css"), header + scope(src));
console.log("wrote src/ui/app.scoped.css");
