import { Audio } from "@remotion/media";
import { AbsoluteFill, Series, staticFile } from "remotion";
import { Atmosphere } from "./components/Atmosphere";
import { sceneFrames } from "./film/timeline";
import { Complexity } from "./scenes/Complexity";
import { EndCard } from "./scenes/EndCard";
import { IntroAgents } from "./scenes/IntroAgents";
import { ScaleSequence } from "./scenes/ScaleSequence";
import { SulcusReveal } from "./scenes/SulcusReveal";
import { UnifiedRuntime } from "./scenes/UnifiedRuntime";
import { colors } from "./theme/colors";

// The film, start to finish. The six scenes share one world and one camera
// (src/film/camera.ts), so every boundary here is a seamless cut. The score
// is generated by scripts/score.ts from the same cue sheet as the picture.
export const SulcusFilm: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: colors.void }}>
    <Series>
      <Series.Sequence
        name="IntroAgents"
        durationInFrames={sceneFrames("IntroAgents").durationInFrames}
      >
        <IntroAgents />
      </Series.Sequence>
      <Series.Sequence
        name="Complexity"
        durationInFrames={sceneFrames("Complexity").durationInFrames}
      >
        <Complexity />
      </Series.Sequence>
      <Series.Sequence
        name="SulcusReveal"
        durationInFrames={sceneFrames("SulcusReveal").durationInFrames}
      >
        <SulcusReveal />
      </Series.Sequence>
      <Series.Sequence
        name="UnifiedRuntime"
        durationInFrames={sceneFrames("UnifiedRuntime").durationInFrames}
      >
        <UnifiedRuntime />
      </Series.Sequence>
      <Series.Sequence
        name="ScaleSequence"
        durationInFrames={sceneFrames("ScaleSequence").durationInFrames}
      >
        <ScaleSequence />
      </Series.Sequence>
      <Series.Sequence
        name="EndCard"
        durationInFrames={sceneFrames("EndCard").durationInFrames}
      >
        <EndCard />
      </Series.Sequence>
    </Series>
    <Atmosphere />
    <Audio src={staticFile("audio/sulcus-score.wav")} />
  </AbsoluteFill>
);
