import { Audio } from "@remotion/media";
import { AbsoluteFill, Series, staticFile } from "remotion";
import { Atmosphere } from "./components/Atmosphere";
import { sceneFrames, type SceneId } from "./film/timeline";
import { Complexity } from "./scenes/Complexity";
import { EndCard } from "./scenes/EndCard";
import { Integrations } from "./scenes/Integrations";
import { IntoSulcus } from "./scenes/IntoSulcus";
import { IntroAgents } from "./scenes/IntroAgents";
import { ManyAgents } from "./scenes/ManyAgents";
import { RunDetailScene } from "./scenes/RunDetailScene";
import { ScaleSequence } from "./scenes/ScaleSequence";
import { Workspace } from "./scenes/Workspace";
import { colors } from "./theme/colors";
import { useFonts } from "./theme/typography";

// The scenes in order. They share one world and one camera
// (src/film/camera.ts), so every boundary here is a seamless cut.
export const SCENE_LIST: [SceneId, React.FC][] = [
  ["IntroAgents", IntroAgents],
  ["Complexity", Complexity],
  ["IntoSulcus", IntoSulcus],
  ["RunDetail", RunDetailScene],
  ["ManyAgents", ManyAgents],
  ["Workspace", Workspace],
  ["Integrations", Integrations],
  ["ScaleSequence", ScaleSequence],
  ["EndCard", EndCard],
];

// The film, start to finish. The score is generated by scripts/score.ts from
// the same cue sheet as the picture.
export const SulcusFilm: React.FC = () => {
  useFonts();
  return (
    <AbsoluteFill style={{ backgroundColor: colors.void }}>
      <Series>
        {SCENE_LIST.map(([id, Scene]) => (
          <Series.Sequence key={id} name={id} durationInFrames={sceneFrames(id).durationInFrames}>
            <Scene />
          </Series.Sequence>
        ))}
      </Series>
      <Atmosphere />
      <Audio src={staticFile("audio/sulcus-score.wav")} />
    </AbsoluteFill>
  );
};
